name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run shell script
      run: |
        #!/bin/bash
        apt-get install -y nodejs
        echo "Hello World From Docker"
