name: Node.js CI

on: pull_request

jobs:
  build:
    runs-on: alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout

      - name: Set up Node.js
        uses: actions/setup-node
        with:
          node-version: "18"

      - name: Install Dependencies and run test
        run: npm ci && npm t

      - name: Run shell script
        run: |
          echo "Hello World Script Running part"
          echo "this is the secret - {{secrets.token}}"
          echo "this is the another secret - {{secrets.sshKey}}"
